// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AccessFromRefreshV1LoginCodeAccessFromRefreshPostData, AccessFromRefreshV1LoginCodeAccessFromRefreshPostErrors, AccessFromRefreshV1LoginCodeAccessFromRefreshPostResponses, AuthenticateV1LoginCodeAuthenticatePostData, AuthenticateV1LoginCodeAuthenticatePostErrors, AuthenticateV1LoginCodeAuthenticatePostResponses, LoginV1LoginCodeRequestPostData, LoginV1LoginCodeRequestPostErrors, LoginV1LoginCodeRequestPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Request a login code
 */
export const loginV1LoginCodeRequestPost = <ThrowOnError extends boolean = false>(options: Options<LoginV1LoginCodeRequestPostData, ThrowOnError>) => (options.client ?? client).post<LoginV1LoginCodeRequestPostResponses, LoginV1LoginCodeRequestPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/login-code/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate
 *
 * Authenticate with a login code.
 */
export const authenticateV1LoginCodeAuthenticatePost = <ThrowOnError extends boolean = false>(options: Options<AuthenticateV1LoginCodeAuthenticatePostData, ThrowOnError>) => (options.client ?? client).post<AuthenticateV1LoginCodeAuthenticatePostResponses, AuthenticateV1LoginCodeAuthenticatePostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/login-code/authenticate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Access From Refresh
 */
export const accessFromRefreshV1LoginCodeAccessFromRefreshPost = <ThrowOnError extends boolean = false>(options: Options<AccessFromRefreshV1LoginCodeAccessFromRefreshPostData, ThrowOnError>) => (options.client ?? client).post<AccessFromRefreshV1LoginCodeAccessFromRefreshPostResponses, AccessFromRefreshV1LoginCodeAccessFromRefreshPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/login-code/access-from-refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
