// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * AuthenticateRequest
 */
export type AuthenticateRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Code
     */
    code: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginCodeRequest
 */
export type LoginCodeRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginV1LoginCodeRequestPostData = {
    body: LoginCodeRequest;
    path?: never;
    query?: never;
    url: '/v1/login-code/request';
};

export type LoginV1LoginCodeRequestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginV1LoginCodeRequestPostError = LoginV1LoginCodeRequestPostErrors[keyof LoginV1LoginCodeRequestPostErrors];

export type LoginV1LoginCodeRequestPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthenticateV1LoginCodeAuthenticatePostData = {
    body: AuthenticateRequest;
    path?: never;
    query?: never;
    url: '/v1/login-code/authenticate';
};

export type AuthenticateV1LoginCodeAuthenticatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthenticateV1LoginCodeAuthenticatePostError = AuthenticateV1LoginCodeAuthenticatePostErrors[keyof AuthenticateV1LoginCodeAuthenticatePostErrors];

export type AuthenticateV1LoginCodeAuthenticatePostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthenticateV1LoginCodeAuthenticatePostResponse = AuthenticateV1LoginCodeAuthenticatePostResponses[keyof AuthenticateV1LoginCodeAuthenticatePostResponses];

export type AccessFromRefreshV1LoginCodeAccessFromRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/v1/login-code/access-from-refresh';
};

export type AccessFromRefreshV1LoginCodeAccessFromRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AccessFromRefreshV1LoginCodeAccessFromRefreshPostError = AccessFromRefreshV1LoginCodeAccessFromRefreshPostErrors[keyof AccessFromRefreshV1LoginCodeAccessFromRefreshPostErrors];

export type AccessFromRefreshV1LoginCodeAccessFromRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
