"""939dab31-d8fe-4ef4-8b21-1d2cef3d952d

Revision ID: 488b2403d5c3
Revises: cd3c5a31aeae
Create Date: 2025-12-27 16:14:51.993811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488b2403d5c3'
down_revision: Union[str, Sequence[str], None] = 'cd3c5a31aeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_login_codes',
    sa.Column('code_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('tbl_login_codes_user_id_fkey'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_login_codes_pkey'))
    )
    op.create_index(op.f('ix_tbl_login_codes_code_hash'), 'tbl_login_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_tbl_login_codes_created_at'), 'tbl_login_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_login_codes_deleted_at'), 'tbl_login_codes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tbl_login_codes_email'), 'tbl_login_codes', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_login_codes_expires_at'), 'tbl_login_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tbl_login_codes_user_id'), 'tbl_login_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_login_codes_user_id'), table_name='tbl_login_codes')
    op.drop_index(op.f('ix_tbl_login_codes_expires_at'), table_name='tbl_login_codes')
    op.drop_index(op.f('ix_tbl_login_codes_email'), table_name='tbl_login_codes')
    op.drop_index(op.f('ix_tbl_login_codes_deleted_at'), table_name='tbl_login_codes')
    op.drop_index(op.f('ix_tbl_login_codes_created_at'), table_name='tbl_login_codes')
    op.drop_index(op.f('ix_tbl_login_codes_code_hash'), table_name='tbl_login_codes')
    op.drop_table('tbl_login_codes')
    # ### end Alembic commands ###
