"""b650b35a-c6d1-4d91-8549-50c65d8cf5c4

Revision ID: 69c95b26e600
Revises: 1cc4c9eb3d5f
Create Date: 2025-12-27 17:30:54.192820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69c95b26e600'
down_revision: Union[str, Sequence[str], None] = '1cc4c9eb3d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user_sessions',
    sa.Column('token', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('tbl_user_sessions_user_id_fkey'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_user_sessions_pkey')),
    sa.UniqueConstraint('token', name=op.f('tbl_user_sessions_token_key'))
    )
    op.create_index(op.f('ix_tbl_user_sessions_created_at'), 'tbl_user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_user_sessions_deleted_at'), 'tbl_user_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tbl_user_sessions_expires_at'), 'tbl_user_sessions', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_deleted_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('token', sa.CHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('user_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey')),
    sa.UniqueConstraint('token', name=op.f('user_sessions_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_deleted_at'), 'user_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_tbl_user_sessions_expires_at'), table_name='tbl_user_sessions')
    op.drop_index(op.f('ix_tbl_user_sessions_deleted_at'), table_name='tbl_user_sessions')
    op.drop_index(op.f('ix_tbl_user_sessions_created_at'), table_name='tbl_user_sessions')
    op.drop_table('tbl_user_sessions')
    # ### end Alembic commands ###
