"""1ec7d339-d962-446d-bbfe-b61a8bfc49a0

Revision ID: ac582cb9e1c3
Revises: 69c95b26e600
Create Date: 2025-12-28 04:54:35.015017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac582cb9e1c3'
down_revision: Union[str, Sequence[str], None] = '69c95b26e600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_sessions_created_at'), table_name='tbl_user_sessions')
    op.drop_index(op.f('ix_tbl_user_sessions_deleted_at'), table_name='tbl_user_sessions')
    op.drop_index(op.f('ix_tbl_user_sessions_expires_at'), table_name='tbl_user_sessions')
    op.drop_table('tbl_user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user_sessions',
    sa.Column('token', sa.CHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('tbl_user_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_user_sessions_pkey')),
    sa.UniqueConstraint('token', name=op.f('tbl_user_sessions_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tbl_user_sessions_expires_at'), 'tbl_user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tbl_user_sessions_deleted_at'), 'tbl_user_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tbl_user_sessions_created_at'), 'tbl_user_sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###
