"""init db and add user table

Revision ID: cd3c5a31aeae
Revises: 
Create Date: 2025-12-27 15:17:18.841698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3c5a31aeae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_users_pkey')),
    sa.UniqueConstraint('email', name=op.f('tbl_users_email_key'))
    )
    op.create_index(op.f('ix_tbl_users_created_at'), 'tbl_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_tbl_users_deleted_at'), 'tbl_users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_users_deleted_at'), table_name='tbl_users')
    op.drop_index(op.f('ix_tbl_users_created_at'), table_name='tbl_users')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
